spring:
  datasource:
    url: ${USER_DATABASE_URL}
    username: ${USER_DATABASE_USERNAME}
    password: ${USER_DATABASE_PASSWORD}
    driver-class-name: ${USER_DATABASE_DRIVER_CLASS_NAME}
eureka:
  instance:
    hostname: ${APP_NAME}.herokuapp.com
userservice:
  api:
    url: ${USER-SERVICE-URL}
    username: ${USER_SERVICE_USERNAME}
    password: ${USER_SERVICE_PASSWORD}